### ISSUE TITLE
Can't launch emacs anywhere

### ISSUE THREAD

**Issue by MasonProtter** [zachcurry/emacs-anywhere#10]
When I try to activate my shortcut I get an error message 

```
The action “Run AppleScript” encountered an error: “emacsclient: could not get terminal name
emacsclient: error executing alternate editor ""”
```

`emacs` and `emacsclient` are both `PATH` variables for me. 

I'm using MacOS 10.13.3

**Comment by zachcurry** [comment]
There is an issue with Automator where it invokes bash with the default PATH variable. Normally dotfiles are run and the PATH is modified to include, for example ‘/usr/local/bin’. My guess is that it’s not finding the same ‘emacsclient’ executable as is when you run ‘emacsclient’ without the shortcut.

Does it work if you run ‘emacsclient’ from terminal without the shortcut? If so, it’s most likely the PATH issue I described.

**Comment by MasonProtter** [comment]
> Does it work if you run ‘emacsclient’ from terminal without the shortcut? If so, it’s most likely the PATH issue I described.

Yeah, I can run `emacsclient` from the terminal no problem, so you're probably right. Do you know a way to fix that?

**Comment by zachcurry** [comment]
The only way I know how to fix this is to do it on our end by running all the scripts which contribute to the path manually before it tries to launch `emacsclient`.

Could you try with these options `emacsclient -a '' -c` in the Terminal and see if that works as well?

**Comment by MasonProtter** [comment]
`emacsclient -a '' -c` works fine.

**Comment by zachcurry** [comment]
Thanks @MasonProtter ! I'll open an issue so we can try to fix the path on our end. In the meantime, if you have both executables in `usr/local/bin` it should allow you to work around this this until I can do something about it on my end.

**Comment by MasonProtter** [comment]
Both `emacs` and `emacsclient` are in `usr/local/bin` for me though...

**Comment by zachcurry** [comment]
That is peculiar 😅

**Comment by MasonProtter** [comment]
This should be independent of whats in my dotfile, correct? I'm asking as I use spacemacs but I don't see how that should have a great effect.

**Comment by MasonProtter** [comment]
Interestingly, if I `M-x server-force-delete` so that I'm no longer running an emacs server, the errormessage I get is different. I end up getting 
```
The action “Run AppleScript” encountered an error: “emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
Loading /Users/mason/.emacs.d/core/core-load-paths.el (source)...
Loading /Users/mason/.emacs.d/core/core-load-paths.el (source)...done
Loading /Users/mason/.spacemacs...
Loading /Users/mason/.spacemacs...done
Open the quickhelp.
Loading /Users/mason/.emacs.d/layers/+lang/python/packages.el (source)...
Loading /Users/mason/.emacs.d/layers/+lang/python/packages.el (source)...done
Loading /Users/mason/.emacs.d/layers/+completion/helm/packages.el (source)...
Loading /Users/mason/.emacs.d/layers/+completion/helm/packages.el (source)...done
Loading /Users/mason/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...
Loading /Users/mason/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done
Loading /Users/mason/.emacs.d/layers/+lang/ipython-notebook/packages.el (source)...
Loading /Users/mason/.emacs.d/layers/+lang/ipython-notebook/packages.el (source)...done
Loading /Users/mason/.emacs.d/layers/+completion/auto-completion/packages.el (source)...
Loading /Users/mason/.emacs.d/layers/+completion/auto-completion/packages.el (source)...done
Loading /Users/mason/.emacs.d/layers/+lang/latex/packages.el (source)...
Loading /Users/mason/.emacs.d/layers/+lang/latex/packages.el (source)...done
Loading /Users/mason/.emacs.d/layers/+distributions/spacemacs/layers.el (source)...
Loading /Users/mason/.emacs.d/layers/+distributions/spacemacs-base/packages.el (source)...
Loading /Users/mason/.emacs.d/layers/+distributions/spacemacs-base/packages.el (source)...done
Loading /Users/mason/.emacs.d/layers/+spacemacs/spacemacs-completion/packages.el (source)...
Loading /Users/mason/.emacs.d/layers/+spacemacs/spacemacs-completion/packages.el (source)...done
Loading /Users/mason/.emacs
```

That last line seems to maybe imply that the problem is that I don't have a .emacs file and instead have a .spacemacs file. Any thoughts?

**Comment by zachcurry** [comment]
I'm running Spacemacs too, so I'm not sure if that's it. I would suggest you open Automator, create a service to run `PATH=/usr/local/bin:$PATH ; emacsclient -a '' -c` and see if you can debug it from there. If it works in Terminal and not when run through Automator, my only guess is that it is a `PATH` issue. Keep me posted and I'll try to do what I can to help 😃

**Comment by MasonProtter** [comment]
So I created a new service which just runs the following shell script:
```
PATH=/usr/local/bin:$PATH ; emacsclient -a '' -c
```

It immediately returns an error
```
The action “Run Shell Script” encountered an error: “emacsclient: could not get terminal name
emacsclient: error executing alternate editor ""”
```

**Comment by zachcurry** [comment]
Damn! One of us should offer this up to Stackoverflow and see if we can get some help with this. So strange!

**Comment by zachcurry** [comment]
What version of Emacs are you rocking?

**Comment by MasonProtter** [comment]
25.2

**Comment by MasonProtter** [comment]
I'll make an SO post

**Comment by zachcurry** [comment]
Thanks! Drop a link and I’ll keep an eye on it

**Comment by MasonProtter** [comment]
https://stackoverflow.com/questions/49079179/opening-emacsclient-in-terminal-works-but-wont-work-with-automator

**Comment by michaelsbradleyjr** [comment]
It's not working consistently for me, for some reason; not sure if the problem is related to the PATH issue or something else.

I'm running macOS 10.13.3, Emacs 25.3.1.

The behavior I'm seeing is that in some contexts, such as the search bar of Console.app, it's working as expected. However, when I try to invoke it in Mail.app or a text input of a web page (tried Chrome, Safari, Firefox), nothing happens.

**Comment by zachcurry** [comment]
I can say with certainty that there are issues in OSX when using multiple displays. Think that might be the issue for you @michaelsbradleyjr ?

**Comment by michaelsbradleyjr** [comment]
I'm only using built-in display of my macbook pro.

**Comment by zachcurry** [comment]
The PATH could be a problem. When Automator invokes shell commands it does not prepare the PATH variable as per usual. I'll open a ticket for this.

Also, someone pointed out to me that the install script fails if not run from the root of the repository. You might check that as well. I've opened an issue for this problem and expect to resolve it soon.

**Comment by tosmi** [comment]
i had a similar problem with "Emacs for MacOS X" and brew emacs installed in parallel. my shell's $PATH points to /usr/local/bin/emacs (installed via brewer). 

emacs anywhere was using /usr/local/bin/emacsclient, so i had to change the call to emacsclient in emacstask to
```
/usr/local/bin/emacsclient -d /private/tmp/com.apple.launchd.dxUxYDU16T/org.macosforge.xquartz:0 -a '' -c -e "(progn $ELISP)"
```
to get it working. i'm now using 
```
/Applications/Emacs.app//Contents/MacOS/bin-x86_64-10_9/emacsclient -a '' -c -e "(progn $ELISP)"
```
in `emacstask` so it uses the emacsclient that comes with 'Emacs for MacOS X'.

there is also an issue with using firefox developer edition. the app name reported is 'firefox'
but switching back only works with 'Firefox Developer Edition' as the name for the app.

so i added 
```
[ "$frontmost_app_name" == "firefox" ] && frontmost_app_name="Firefox Developer Edition"
```
to `~/.emacs_anywhere/bin/run`.

hth
toni

**Comment by MasonProtter** [comment]
Okay I finally figure it out.

I changed the script from 
```
PATH=/usr/local/bin:$PATH ; emacsclient -a '' -c
```
to 
```
do shell script "/usr/local/bin/emacsclient -a \"\" -c --display ns
```

and that did the trick.

**Comment by zachcurry** [comment]
@MasonProtter are you still having this problem with the latest on master? If so, maybe we can put a config file to allow users to explicitly define their path to the executable as well as custom options like `--display ns`.

**Comment by zachcurry** [comment]
@MasonProtter  @michaelsbradleyjr @tosmi  you can now configure the way **Emacs Anywhere** invokes **emacsclient**.   Get the latest from master and have a look at the section in the **README** titled "Configure". I'm 99.9% sure this will fix your issue(s).
