### ISSUE TITLE
Errors when running install script on GNU/Linux

### ISSUE THREAD

**Issue by trentandraka** [zachcurry/emacs-anywhere#12]
When I run the install script (through `./emacs_anywhere/install`) on my system (Manjaro Linux), I get the following errors (before it says it was successfully installed anyways):

```
cp: cannot stat '/home/trentandraka/emacs_anywhere.el': No such file or directory
cp: cannot stat '/home/trentandraka/bin/emacstask': No such file or directory
cp: cannot stat '/home/trentandraka/bin/linux': No such file or directory
Emacs Anywhere has been installed
```
It wasn't installed correctly, however, since trying to set the shortcut with the provided terminal command doesn't work. What's the fix?

I get that the GNU/Linux release is still in alpha, just wanted to point this out and provide feedback that is hopefully of use.

**Comment by zachcurry** [comment]
You did the right thing! If you get a chance have a look at the install script and see anything stands out as the likely cause. Thanks 🙏

**Comment by psibi** [comment]
Another data point: Installation work fine on my Ubuntu machine.

**Comment by reedlaw** [comment]
I `cd`'ed to `./emacs_anywhere` and ran `./install` and the files were copied correctly. But I could not get it to launch via keyboard shortcut (Arch Linux).
