### ISSUE TITLE
Didn't work on my Linux setup

### ISSUE THREAD

**Issue by psibi** [zachcurry/emacs-anywhere#18]
I have an xmonad setup on top of Ubuntu. I debugged and found that the reason why it wasn't working on my machine: After the elisp command `(kill-buffer "*Emacs Anywhere*")` gets executed, the X clipboard doesn't have anything in the clipboard. I changed the algorithm slightly like this:

```
(require 'f)

(defun ea-on-delete (frame)
  (f-write (buffer-string) 'utf-8 "~/.emacs_anywhere/clipboard"))
```

And then it started working. Ofcourse, I also had to change the `run` command accordingly. Honestly, I find relying on Clipboard in Linux to be troublesome. I can send you a PR if you agree to change the logic the above way.

**Comment by beshrkayali** [comment]
Same for me on my Arch setup. I also thought that it'd be better to just write to file and not mess with clipboards, but I'm having an issue with `xdotool type` bungling the insertion of newline chars and I'm curious to know how you got the `run` script working.

Here's my version of it:
```
...
xdotool windowactivate --sync $window type "$(cat ~/.emacs_anywhere/text)"
```

**Comment by psibi** [comment]
@beshrkayali  I modified the run command to this:

```
#!/usr/bin/env bash

window=$( xdotool getwindowfocus )

$HOME/.emacs_anywhere/bin/emacstask

xdotool windowfocus --sync $window

clipboard=$( cat $HOME/.emacs_anywhere/clipboard )

xdotool type "$clipboard"
```

Let me know if that works for you!

**Comment by beshrkayali** [comment]
hmm.. looks similar to what I have, but strangely, `xdotool` is not inserting newlines properly. I think most likely because of this https://unix.stackexchange.com/a/399638.

**Comment by psibi** [comment]
@beshrkayali Oh yeah, just noticing it. Even my setup doesn't insert newlines properly. Would love to know if  you would come up with any workaround.

**Comment by beshrkayali** [comment]
@psibi Yep! I borrowed the one-liner from Gilles answer, which basically replaced newlines chars with carriage returns.

Here's how it looks now:
```
#!/bin/bash
window=$( xdotool getwindowfocus)
$HOME/.emacs_anywhere/bin/emacstask
xdotool windowactivate --sync $window type "$(cat ~/.emacs_anywhere/text | tr \\n \\r | sed s/\\r*\$//)"
```

**Comment by psibi** [comment]
Awesome!

That works. This comment is from Emacs. :-)

**Comment by BontaVlad** [comment]
@beshrkayali  solution works great, but if you want to skip "typing" long buffers and have xclip on hand 
```
#!/bin/bash
window=$( xdotool getwindowfocus)
$HOME/.emacs_anywhere/bin/emacstask
xdotool windowfocus --sync $window
xclip -sel clip ~/.emacs_anywhere/text
xdotool key --clearmodifiers ctrl+v

```

**Comment by psibi** [comment]
@BontaVlad The problem with your approach is that it won't work for all applications. For `gnome-terminal`, the paste command is `Shift + Ctrl + V`. Also using clipboard mechanism is not that reliable in a Linux machine. Also in my experience, debugging errors from `xclip` has always been painful.

**Comment by zachcurry** [comment]
Thanks! Send a pull request if you think it will help others avoid the same issue. Glad you got it working @psibi !

**Comment by BontaVlad** [comment]
@psibi I agree. What I proposed should not be taken as a general, solve all solution, it's just a quick hack to solve my use case and maybe should prove useful for some other internaut. My scenario for using emacs anywhere usually involves long text edits so making xdotool type everything either takes to long  or "skips" a letter or two.

**Comment by beshrkayali** [comment]
@BontaVlad  @psibi 
True, but I still prefer not to mess with clipboards or replace previously held text.

Adding a `--delay 1` (default is 12ms) somewhat solves the issue of long-ish text:

```
xdotool windowactivate --sync $window type --delay 1 "$(cat ~/.emacs_anywhere/text | tr \\n \\r | sed s/\\r*\$//)"
```

**Comment by psibi** [comment]
@beshrkayali @BontaVlad Have sent a PR with some improvements for Linux: https://github.com/zachcurry/emacs-anywhere/pull/23

Let me know if something there concerns you or can be improved.

**Comment by beshrkayali** [comment]
@psibi looks good!

One small issue is that the manpage for `xdotool` suggests that `getactivewindow` is more reliable than `getwindowfocus`. I have not found this to be the case however (I'm running i3), it's the opposite actually.

Not exactly sure why or if it might affect other window managers.

**Comment by psibi** [comment]
@beshrkayali 

> One small issue is that the manpage for xdotool suggests that getactivewindow is more reliable than getwindowfocus. I have not found this to be the case however (I'm running i3), it's the opposite actually.

I agree! In fact `getactivewindow` was failing in my setup too (XMonad). Thanks for the review. :-)

**Comment by DavidLarsson** [comment]
Further comments on the PR: [PR tests](https://github.com/zachcurry/emacs-anywhere/pull/23#issuecomment-371749814)

**Comment by zachcurry** [comment]
At this point I'm not ready to adopt this alternative. When I get the time I'll look into the efficacy of avoiding the clipboard. Thanks!
