### ISSUE TITLE
Install and uninstall scripts fail when not run from the root of the repo

### ISSUE THREAD

**Issue by gisborne** [zachcurry/emacs-anywhere#25]
```
$ ./emacs-anywhere/install
cp: /Users/gisborne/emacs_anywhere.el: No such file or directory
cp: /Users/gisborne/bin/emacstask: No such file or directory
cp: /Users/gisborne/bin/osx: No such file or directory
cp: /Users/gisborne/Emacs Anywhere.workflow: No such file or directory
Emacs Anywhere has been installed
```

**Comment by zachcurry** [comment]
Thanks @gisborne ! I'll take a look at this.

Trying running install from within the repository and see if that fixes it
``` bash
./install
```
If it does, we'll need to open an issue to update the install script not to care where it is called from.

**Comment by fiveNinePlusR** [comment]
it fails for me as well on osx but for different reasons...

`zsh: ./install: bad interpreter: /bin/bash^M: no such file or directory`

and same when running it inside bash

**Comment by gisborne** [comment]
On Mar 4, 2018, at 14:35 , Zach Curry <notifications@github.com> wrote:
> 
> Thanks @gisborne <https://github.com/gisborne> ! I'll take a look at this.
> 
> Trying running install from within the repository and see if that fixes it
> 
> ./install
> If it does, we'll need to open an issue to update the install script not to care where it is called from.
> 
$ cd emacs-anywhere/
gisborne at Hermes in ~/emacs-anywhere on master*
$ ./install
Emacs Anywhere has been installed # this isn’t correct
gisborne at Hermes in ~/emacs-anywhere on master*
$ ./uninstall
./uninstall: line 5: syntax error in conditional expression
./uninstall: line 6: syntax error near `then'
./uninstall: line 6: `then’

# deploy fix in https://github.com/zachcurry/emacs-anywhere/pull/26 <https://github.com/zachcurry/emacs-anywhere/pull/26>

$ ./uninstall
Emacs Anywhere has been uninstalled
gisborne at Hermes in ~/emacs-anywhere on master*
$ ./install
Emacs Anywhere has been installed

**Comment by fiveNinePlusR** [comment]
my line endings are dos for some reason instead of what they should be as unix line endings.

**Comment by fiveNinePlusR** [comment]
to clarify, mine does fail when run from the root of the repo using `./install`
