### ISSUE TITLE
Edit text

### ISSUE THREAD

**Issue by jaimehrubiks** [zachcurry/emacs-anywhere#27]
I don't know what you think but, I've thought about whether it would be better if selected text (or text in a text field) should be pre-inserted in emacs or not. Another idea could be to provide a settings for emacs-everywhere to choose things like this.
The current alternative isn't that bad either, one must just select and copy the text, and then paste it on emacs, after it would be replaced because it was selected before insertion.

**Comment by zachcurry** [comment]
Hi @jaimehrubiks ! I think this issue is similar to [#3](https://github.com/zachcurry/emacs-anywhere/issues/3). Thanks!

**Comment by jaimehrubiks** [comment]
I didn´t see that issue! I´ll close then. Thanks.

**Comment by jaimehrubiks** [comment]
By the way, I am really enjoying this software, it is so fun!. Thanks.

**Comment by zachcurry** [comment]
I’m  really happy you’re getting some use out of it! And I appreciate you getting involved and helping us out. Thank you!
