### ISSUE TITLE
Automatically pick major mode

### ISSUE THREAD

**Issue by Fuco1** [zachcurry/emacs-anywhere#39]
I'm not sure what our options are but it would be super cool if I could execute this on say github comment box and the frame would pop up in `gfm-mode` automatically.

I think if we could somehow pass the window title (`xwininfo` can grab that) or some other properties to some callback/hook then we could configure this in our own emacs configs (because we are using the `emacsclient` here).

This package could come with some preconfigured setup that the user would just enable or they can create their own.

What do you think?

**Comment by zachcurry** [comment]
Let me start by saying that I'm a big fan of your work @Fuco1 ! You have added a lot of value to what I get out of Emacs!

Just to give some quick context, this is my first Gtihub repo and my skills with bash, elisp, and Emacs are elementary at best. I could really use the guidance of someone of someone like yourself. 

I agree that it would be cool to have some logic/config to set the major mode. I've never considered looking at the window titles but it sounds like a great idea! I will defer to your judgement on how this should me achieved.

Thanks @Fuco1 !

**Comment by Fuco1** [comment]
Oh, thanks! :blush: 

I think a start would be to define a hook variable and add a call to that (using `run-hook-with-args`) in the `progn` you pass to emacsclient to execute.

Next step would be to somehow bake the window title as the argument.  This could probably be done by interpolating it as a constant in the bash script.

**Comment by zachcurry** [comment]
Your advice was very helpful @Fuco1 !. I've got this working in OS X and it's pretty sweet! I'm really glad you thought of this feature!

At the moment I'm passing both the application name and window title to the hook functions since I've found the window title can be just about anything depending on the context and the application. Let me know if you have any concerns about this or if this is not what you'd had in mind.

I'll switch over to Linux and try to get that working as soon as I can.  I'll start by checking out **xwininfo** as you suggested.

**Comment by Fuco1** [comment]
@zachcurry Very cool!  You can open a pull request or push a branch if you have any troubles so I can review it, I'd be more than happy to!

**Comment by zachcurry** [comment]
@Fuco1 I'm pushing and making a PR right now. Any help will be greatly appreciated! I know I don't know anything about bash or Emacs Lisp so, don't hesitate to school me on this stuff! If you want feel free to push to this project at will; no need to run it by me.

**Comment by Fuco1** [comment]
I think this can now be closed @zachcurry ? Awesome work in #40!

**Comment by zachcurry** [comment]
@Fuco1 I can't thank you enough for suggesting this feature and acting as my remote code sensei in #40. Epic contribution my friend!

**Comment by zachcurry** [comment]
Also, I'm thinking about adding an achievements section to the README (like spacemacs has). I hope you don't mind if I put this in there as my all time favorite feature request 😄

**Comment by Fuco1** [comment]
That's a good idea, I'll finally become famous! :heart_eyes:
