### ISSUE TITLE
not working with ubuntu

### ISSUE THREAD

**Issue by samwalrus** [zachcurry/emacs-anywhere#51]
I am unable to get this to work in Ubuntu. I can not install the dependencies xprop and xwininfo which may be the reason. 
$ sudo apt-get install xprop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package xprop

sudo apt-get install xwininfoReading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package xwininfo

**Comment by zachcurry** [comment]
Hi @samwalrus !

Give me a moment to fire up my VM and test this...

**Comment by zachcurry** [comment]
@samwalrus, clearly I messed up writing the README. **xprop** and **xwininfo** seem to be included in another package for **xorg**. Try these two commands to see if you've already got them.
```
type xprop
type xwininfo
```
This should return the path for each, if it exists.

I really appreciate you bring this to my attention btw! 👍
