### ISSUE TITLE
More robust pasting

### ISSUE THREAD

**Issue by tecosaur** [zachcurry/emacs-anywhere#65]
Hello,

I notice that ATM, we use `Ctrl+v` for pasting. Quite a few apps (e.g. emacs, terminal) use that for something else. It seems that a much safer method (used by CopyQ) is to use `Shift+Insert`. 
https://github.com/zachcurry/emacs-anywhere/blob/05bf8ef119834d330803bdad91f9028ff87cc7b9/bin/linux#L47

Perhaps this should be used instead?

**Comment by sickerin** [comment]
I second this, I've swapped my ctrl and capslock, and for some reason using ctrl+v results in "V" being pasted. Modifying it to Shift + Insert makes it work. I've also found that it doesn't work in applications where the shortcut for paste isn't ctrl+v. Shift + Insert is probably more universal.
