### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by zachcurry** [zachcurry/emacs-anywhere#7]

**Comment by zeltak** [comment]
Hi, thx so much for this effort. I dont know how to program but would love to help in other ways (testing etc) since this could be really cool and useful

best

Z

**Comment by zachcurry** [comment]
That sounds awesome @zeltak ! As soon as we can get it working, we’ll need to test this out in Linux. Also, the README could always use some work. It’s really cool of you to offer to help! 👍

**Comment by DavidLarsson** [comment]
Hi! This seems like a really worthwhile project. I use Emacs daily and using it everywhere is something I would want. Do you have anyone working on a Linux version (I run Ubuntu 16.04) or any ideas on where to get started? I'm really interested in getting going on this. I think a first thing to consider is if the different desktop environments need to be handled differently from one another.

**Comment by zachcurry** [comment]
Hi @DavidLarsson ! It's awesome to hear you are optimistic about this project's utility!

I'm going to push a branch to get us started with this sometime today. Feel free to contribute and discuss as the work unfolds. 

Right now, there is just a dmg and little script I wrote (hacked) just to make this thing work for me in OSX. We need to write bash script to check the OS it's running in and install accordingly.  The service for OSX already exists, it just needs to be separated from the Elisp, so that will be a breeze. 

Most of the work will be implementing the app refocus and paste functionality in Linux, which is a problem plenty before us have solved before. And I think it would be nice to set a default keyboard shortcut for both OSX and Linux.

Something to keep in mind while we do this is that we will want to package this thing up (soon) for Homebrew, if not other package managers further down the road.

**Comment by zachcurry** [comment]
@zeltak, @DavidLarsson could you test [#9](https://github.com/zachcurry/emacs-anywhere/pull/9) on Linux if you get a chance?

**Comment by zeltak** [comment]
Hi @zachcurry  

i tested on arch linux (dont have an ubuntu machine but can test mondat at work).
it installs well and the keybind pops up the emacs frame.
yet i cant seem to get the text to be pasted in the previous source window. i tried both M-x `delete-frame` and just closing with no success

happy to keep debugging!

Z
